name: MinewebBridge
main: fr.vmarchaud.mineweb.bukkit.BukkitCore
version: 3.0.1
authors:
  - ThisIsMac
  - Shyrogan
softdepend:
  - ProtocolLib
commands:
  mineweb:
    description: Commands to manage MineWebBridge
    usage: |
      Use /help mineweb [subcommand] for more information
      /mineweb reset - Reset the link
      /mineweb port <port> - Setup custom port
  mineweb reset:
    description: Reset plugin configuration
    usage: /mineweb reset
    permission: mineweb.reset
  mineweb port:
    description: Setup custom port
    usage: /mineweb port <port>
    permission: mineweb.port